elasticsearch:
  image: elasticsearch:1.7
  ports:
    - 9200:9200
  volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data:rw
  working_dir: /usr/share/elasticsearch/data

kibana:
  image: kibana:4.1
  links:
    - elasticsearch
  ports:
    - 5601:5601

logstash:
  image: logstash:1.5.3
  command: logstash -f /etc/logstash/conf.d
  volumes:
    - ./logstash:/etc/logstash:ro
  links:
    - elasticsearch
  ports:
    - 1025:1025

proxy:
  image: sameersbn/squid:latest
  volumes:
    - ./proxy/squid.user.conf:/etc/squid3/squid.user.conf:ro
    - ./data/proxy/squid/cache:/var/spool/squid3:rw
  links:
    - logstash
  ports:
    - 3128:3128
